[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "$version"

update_changelog_on_bump = true
changelog_incremental = true
version_files = [
    ".cz.toml:version",
    "package.json:version"
]